"""Transcribe fonts and mouth bitmaps from the Mark 1 Arduino firmware.

Usage: python scripts/port_firmware_tables.py <path-to-enclosure-mark1-checkout>

Regenerates ovos_virtual_mark1/fonts.py and ovos_virtual_mark1/mouth_images.py
from https://github.com/MycroftAI/enclosure-mark1 so the tables are verifiably
identical to what the real hardware renders.
"""

import re
import sys
from pathlib import Path

PACKAGE_DIR = Path(__file__).resolve().parent.parent / "ovos_virtual_mark1"
HEADER = '"""Generated by scripts/port_firmware_tables.py from MycroftAI/enclosure-mark1. Do not edit."""\n'
NIBBLE = re.compile(r"0b([01]{4})")
BLOCK_COMMENT = re.compile(r"/\*.*?\*/", re.DOTALL)
LINE_COMMENT = re.compile(r"//[^\n]*")


def strip_comments(source: str) -> str:
    return LINE_COMMENT.sub("", BLOCK_COMMENT.sub("", source))


def c_array_body(source: str, name: str) -> str:
    match = re.search(name + r"\[\](?:\[16\])?\s*=\s*\{(.*?)\n\};", source, re.DOTALL)
    if not match:
        raise SystemExit(f"array {name} not found")
    return match.group(1)


def nibbles(body: str) -> list[int]:
    return [int(bits, 2) for bits in NIBBLE.findall(body)]


def widths(body: str) -> list[int]:
    return [int(n) for n in re.findall(r"\d+", body)]


def plates(body: str) -> list[list[int]]:
    values = nibbles(body)
    if len(values) % 16:
        raise SystemExit("plate data is not a multiple of 16 nibbles")
    return [values[i : i + 16] for i in range(0, len(values), 16)]


def fmt_rows(rows: list[list[int]], indent: str = "    ") -> str:
    return ",\n".join(indent + "[" + ", ".join(str(v) for v in row) + "]" for row in rows)


def render_fonts(firmware: Path) -> str:
    out = [HEADER, "from ovos_virtual_mark1.framebuffer import Font\n"]
    for stem, height in (("5x4", 5), ("8x4", 8)):
        source = strip_comments((firmware / "lib/HT1632" / f"font_{stem}.h").read_text())
        glyphs = nibbles(c_array_body(source, f"FONT_{stem.upper()}"))
        glyph_widths = widths(c_array_body(source, f"FONT_{stem.upper()}_WIDTH"))
        if len(glyphs) != 64 * 10 or len(glyph_widths) != 64:
            raise SystemExit(f"font {stem}: unexpected glyph count")
        rows = [glyphs[i : i + 10] for i in range(0, 640, 10)]
        out.append(f"\nFONT_{stem.upper()} = Font(\n    height={height},\n    glyph_step=10,\n")
        out.append("    glyphs=[\n" + fmt_rows(rows, "        ") + ",\n    ],\n")
        out.append("    widths=[" + ", ".join(map(str, glyph_widths)) + "],\n)\n")
    return "".join(out)


def render_mouth_images(firmware: Path) -> str:
    source = strip_comments((firmware / "lib/MycroftMouth/MouthImages.h").read_text())
    out = [HEADER, "\n# Each entry is one 8x8 plate: 16 nibbles, column-major, low bit = top pixel.\n"]
    for name in ("LISTEN_ANIMATION", "TALK_ANIMATION", "THINK_ANIMATION", "MOUTH_VISEMES"):
        out.append(f"\n{name} = [\n" + fmt_rows(plates(c_array_body(source, name))) + ",\n]\n")
    return "".join(out)


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    firmware = Path(sys.argv[1])
    (PACKAGE_DIR / "fonts.py").write_text(render_fonts(firmware))
    (PACKAGE_DIR / "mouth_images.py").write_text(render_mouth_images(firmware))
    print("wrote fonts.py and mouth_images.py")


if __name__ == "__main__":
    main()
